### ISSUE TITLE
Feature request: Add support for reading the state from Switchbot devices

### ISSUE THREAD

**Issue by moretea** [Danielhiversen/pySwitchbot#18]
Based on the observed behavior in the Switchbot app, it must be possible to query for the current state from the Switchbot devices. 

I'm not intimately familiar (yet) with BLE, but from what I gather, we could fetch these as characteristics. This poses the question of the impact on battery life if we poll to often.

**Comment by basvdl** [comment]
I have succeeded reading the battery, position and light level using the python package bleak. The `bluepy` package is not working for me, it does not fetch any advertisement data regarding battery, position or light level. I'm new to bluetooth communications, so I might have done something wrong using `bluepy`. I also like bleak more, since it works cross platform, whereis `bluepy` only works on Linux.

**Comment by oetelaar24** [comment]
Hi, I'm really keen on trying this additional functionality out. Any chance you are willing to make a new release containing it?

**Comment by Danielhiversen** [comment]
PySwitchbot 0.10.0 is now released
